import React from 'react'
import NumPanel from './NumPanel'

function GameBoard() {
  return (
    <div className='w-5/12 p-3 rounded bg-zinc-900  aspect-square grid  grid-cols-10 grid-rows-10 gap-1'>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
        <NumPanel/>
    </div>
  )
}

export default GameBoard